### ISSUE TITLE
Create Guides Template

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs-site#176]
A bit self explanatory. It would behoove us to have a template/skeleton for guides, much like we do for plugins.

**Comment by mbbroberg** [comment]
One must if we are going to be hosting Guides: **sane defaults.** 

With these in place, we avoid needing to replicate every guide for every operating system, configuration management, cloud environment or other switch point. 

It will also be helpful to commit to a few expectations: guides are submitted for one or more version of Sensu, though there's no requirement to continue them on to the next release. 

These commitments can be outlined in our CONTRIBUTING.md file

**Comment by asachs01** [comment]
Fixed by #181
