### ISSUE TITLE
Alternate banner needed for pre-release products

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs-site#226]
![2018-02-28 at 10 01 am](https://user-images.githubusercontent.com/148017/36805553-f25339b4-1c7a-11e8-9b6c-5bd397236b17.png)

The "older version" banner visible here isn't quite right. It would be nice to differentiate pre-release (alpha, beta) products.

**Comment by dabria** [comment]
I have a WIP branch (that really needs to be updated) that I had paused work on for: #94 it was going to allow customization of text and colour. This could be reused for this purpose.

I could probably look into this next week or pass the partially finished branch to someone cc @grepory
