### ISSUE TITLE
Search isn't working

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs-site#279]
There appears to be something wrong with the search function. I'm seeing the following in javascript error console

![2018-03-20 at 1 50 pm](https://user-images.githubusercontent.com/148017/37679170-c7d0898c-2c45-11e8-8b24-60922023a83e.png)

The JSON search index seems to be available at https://docs.sensu.io/js/lunr/PagesIndex.json, so I'm not sure whats going on.

**Comment by jamesdphillips** [comment]
looks like there are a number of `null` values in the JSON
