### ISSUE TITLE
Migrate Enterprise Dashboard content to Sensu Enterprise Dashboard product

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs-site#81]
We've ported over the Sensu Enterprise documentation content from sensu-docs, but left the old structure intact. We need to 

- [x] Identify content under Enterprise which belongs in Enterprise Dashboard docs
- [x] Determine which version(s) of Sensu Enterprise Dashboard correlate to supported versions of Sensu Enterprise (2.6+)
- [x] Move identified content from Sensu Enterprise to Sensu Enterprise Dashboard
- [x] Reorganize content under Enterprise Dashboard so that menus look ok and flow is reasonable

**Comment by Blue0ctober** [comment]
Content that needs to be moved:
[ ] hud.md 
[ ] rbac.md
[ ] sensu-enterprise-dashboard configuration from configuration.md

**Comment by Blue0ctober** [comment]
Still needs to be done:

- [ ] Migrate HUD docs
- [ ] Migrate Collections
- [ ] Migrate Sensu Dashboard (remove from sensu ent docs)
- [ ] Merge changes from 2.8

**Comment by cwjohnston** [comment]
Closed by #148
